
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CC0091:Make 'GetJim' method static.", Justification = "<Pending>", Scope = "member", Target = "~M:CodeCrackerSamples.Class1.GetJim~CodeCrackerSamples.Person")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CC0057:Parameter 'minAge' is not used.", Justification = "<Pending>", Scope = "member", Target = "~M:CodeCrackerSamples.Person.CanVote(System.Int32)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CC0091:Make 'SayHello' method static.", Justification = "<Pending>", Scope = "member", Target = "~M:CodeCrackerSamples.Person.SayHello~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CC0091:Make 'TestSqlCommand' method static.", Justification = "<Pending>", Scope = "member", Target = "~M:LanguageFeaturesCS.TSqlAnalyzerTests.TestSqlCommand")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CC0091:Make 'AnotherMethod' method static.", Justification = "<Pending>", Scope = "member", Target = "~M:LanguageFeaturesCS.UnorderedClass.AnotherMethod")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CC0091:Make 'TestContextBad' method static.", Justification = "<Pending>", Scope = "member", Target = "~M:TestProject.LinqTests.TestContextBad")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CC0011:You can remove 'Where' moving the predicate to 'FirstOrDefault'.", Justification = "<Pending>", Scope = "member", Target = "~M:TestProject.LinqTests.TestContextBad")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CC0022:Context should be disposed.", Justification = "<Pending>", Scope = "member", Target = "~M:TestProject.LinqTests.TestContextBad")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CC0021:Use 'nameof(Age)' instead of specifying the program element name.", Justification = "<Pending>", Scope = "member", Target = "~M:TestProject.Person.IsOld~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "CodeCrackerSamples")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "LanguageFeaturesCS")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CodeCrackerSamples.Class1.#GetJim()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "CodeCrackerSamples.Class1.#GetJim()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.Write(System.String)", Scope = "member", Target = "CodeCrackerSamples.Class1.#ShouldUseVar(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "CodeCrackerSamples.Class1.#ShouldUseVar(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "CodeCrackerSamples.Class1.#ShouldUseVar(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "CodeCrackerSamples.Class1.#ShouldUseVar(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object,System.Object)", Scope = "member", Target = "CodeCrackerSamples.Class1.#ShouldUseVar(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "minAge", Scope = "member", Target = "CodeCrackerSamples.Person.#CanVote(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "CodeCrackerSamples.Person.#SayHello()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "LanguageFeaturesCS.TSqlAnalyzerTests.#TestSqlCommand()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "LanguageFeaturesCS.UnorderedClass.#AnotherMethod()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "LanguageFeaturesCS.UnorderedClass.#aRandomField")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object,System.Object)", Scope = "member", Target = "LanguageFeaturesCS.UnorderedClass.#FullName()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "TestProject.Foo.#.ctor(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "TestProject.Foo.#_Xx")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "bar", Scope = "member", Target = "TestProject.Foo.#bar")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors", Scope = "type", Target = "TestProject.LanguageImprovement")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "TestProject.LinqTests.#TestContextBad()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "TestProject.LinqTests.#TestContextBad()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "filtered", Scope = "member", Target = "TestProject.LinqTests.#TestContextBad()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "people", Scope = "member", Target = "TestProject.LinqTests.#TestContextBad()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object,System.Object)", Scope = "member", Target = "TestProject.Person.#FullName()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "TestProject.Person.#IsOld()")]

